version: '3.8'

volumes:
  vendor:
  node_modules:

services:
  nginx:
    image: nginx
    volumes:
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./:/var/www/
    restart: unless-stopped
    ports:
      - "8871:80"
    depends_on:
      - app
    container_name: app_nginx
    
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
      - vendor:/var/www/vendor
    container_name: app_laravel

  node:
    build:
        context: .
        dockerfile: _docker/nodejs/Dockerfile
    tty: true
    ports:
        - "5173:5173"
    working_dir: /var/www
    volumes:
        - .:/var/www
        - node_modules:/var/www/node_modules
    container_name: app_node
    depends_on:
      # - nginx
      - app

  websocket:
    build:
      dockerfile: _docker/websockets/Dockerfile
      context: ./
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - vendor:/var/www/vendor
    ports:
      - 6001:6001
    container_name: app_websocket

  redis:
    image: redis:alpine
    volumes:
      - ./:/var/www
    ports:
      - "6379:6379"
    restart: unless-stopped
    container_name: app_redis
    depends_on:
      - app